[package]
name = "cam-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
cam-core = { path = "../cam-core" }
eframe = "0.33.3"
egui_extras = { version = "0.33.3", features = ["all_loaders"] }
resvg = "0.45"
tiny-skia = "0.11"
rfd = "0.14"
